Fix changing keys during iteration in matchmaker heartbeat
When starting heartbeat in matchmaker-redis, keys may be changed
during iteration and a runtime exception is thrown as follows:

RuntimeError: dictionary changed size during iteration

Change-Id: I016a449674619294196055614c62c2856002291c
Closes-Bug: #1432966
(cherry picked from commit 72a9984d8f28933fadf0f186bc40cc3454fc9353)